apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: default
data:
  nginx.conf: |
    worker_processes auto;
    events {
      worker_connections 1024;
    }
    http {
   
      sendfile on;

       upstream backend {
       server myapp-7cf4c4fbdc-b5fkm:8080;
       server kibana-644f7c776-p7wcb:8080;
       server elasticsearch-7dcdbd57f6-gq6fr:5601;
      }
      server {
        listen 80;
        server_name http://34.168.240.71/ ;

      location /backend {
      proxy_pass http://backend;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
      }
    }


