apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: default
data:
  nginx.conf: |
    worker_processes 1;
    events {
      worker_connections 1024;
     }
    http {
   
      sendfile on;

       upstream kibana {
       server kibana-644f7c776-dxhxg:5601;
      }
       upstream myapp-service {
       server myapp-7cf4c4fbdc-hsnb6:8080;
      }
       upstream elasticsearch {
       server elasticsearch-7dcdbd57f6-2lp5k:5601;
      }
      server {
       listen 80;
       server_name www.my-webserver.com;
        
       location /kibana {
        proxy_pass http://kibana;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
         }
       location /myapp-service {
        proxy_pass http://myapp-service;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
       }
       location /elasticsearch {
        proxy_pass http://elasticsearch;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
       }
      }
    }


