apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: default
data:
  nginx.conf: |
    worker_processes 1;
    events {
      worker_connections 1024;
     }
    http {
   
      sendfile on;

      upstream kibana {
        server kibana:5601;
      }
      upstream myapp-service {
        index index.html;
        root /usr/share/nginx/html
      }
      upstream elasticsearch {
        server elasticsearch:5601;
      }
      server {
       listen 80;
       server_name www.my-webserver.com;
        
        location /kibana/ {
         proxy_pass http://kibana/;
         proxy_set_header Host $host;
         proxy_set_header X-Real-IP $remote_addr;
         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
         proxy_set_header X-Forwarded-Proto $scheme;
         proxy_connect_timeout 30;
         proxy_send_timeout 30;
        }
        location /myapp-service/ {
         proxy_pass http://myapp-service/;
         proxy_set_header Host $host;
         proxy_set_header X-Real-IP $remote_addr;
         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
         proxy_set_header X-Forwarded-Proto $scheme;
         proxy_connect_timeout 30;
         proxy_send_timeout 30;
        }
        location /elasticsearch/ {
         proxy_pass http://elasticsearch/;
         proxy_set_header Host $host;
         proxy_set_header X-Real-IP $remote_addr;
         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
         proxy_set_header X-Forwarded-Proto $scheme;
         proxy_connect_timeout 30;
         proxy_send_timeout 30;       
        }
      }
    }


