apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: default
  spec:
    worker_processes 1;
    events {
      worker_connections 1024;
    }
    http {
   
      sendfile on;

       upstream backend {
       server myapp-service:8080;
       server kibana:5601;
      }
      server {
        listen 80;
        server_name myserver.com;

      location / {
      proxy_pass http://backend;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
      }
    }


