apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: default
data:
  nginx.conf: |
    worker_processes 1;
    events {
      worker_connections 1024;
    }
    http {
   
      sendfile on;

       upstream backend {
       server myapp-7cf4c4fbdc-b5fkm:8080;
       server kibana-644f7c776-p7wcb:8080;
       server elasticsearch-7dcdbd57f6-gq6fr:8080;
      }
      server {
        listen 80;
        server_name myserver.com;

        location / {
          root /usr/share/nginx/html;
          index index.html;
        }
        location /myapp-7cf4c4fbdc-b5fkm {
          proxy_pass http://backend;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
        }

        location /kibana-644f7c776-p7wcb {
           proxy_pass http://backend;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
        }

          location /elasticsearch-7dcdbd57f6-gq6fr {
           proxy_pass http://backend;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
        }
      }
    }


