apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: default
data:
  nginx.conf: |
    worker_processes 1;
    events {
      worker_connections 1024;
     }
    http {
   
      sendfile on;

       upstream kibana {
       server 34.83.157.87:5601/;
      }
       upstream myapp-service {
       server 35.197.123.227:8080/;
      }
       upstream elasticsearch {
       server elasticsearch:5601;
      }
      server {
       listen 80;
       server_name www.my-webserver.com;
        
       location /kibana {
        proxy_pass http://kibana;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
         }
       location /myapp-service {
        proxy_pass http://myapp-service;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
       }
       location /elasticsearch {
        proxy_pass http://elasticsearch;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
       }
      }
    }


