apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: default
data:
  nginx.conf: |
    worker_processes 1;
    events {
      worker_connections 1024;
    }
    http {
      appstream app1 {
        server app1-service:8080;
      }
      appstream app2 {
        server app2-service:8080;
      }
      server {
        listen 80;
        server_name myserver.com;

        location / {
          root /usr/share/nginx/html;
          index index.html;
        }
        location /app1 {
          proxy_pass http://app1;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
        }

        location /app2 {
          proxy_pass http://app2;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
        }
      }
    }


